# Generated by Django 4.2.7 on 2024-12-29 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("event_name", models.CharField(max_length=200)),
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "event_image_1",
                    models.ImageField(null=True, upload_to="event_images"),
                ),
                (
                    "event_image_2",
                    models.ImageField(null=True, upload_to="event_images"),
                ),
                ("event_date", models.DateTimeField(null=True)),
                ("organised_by", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
