# Generated by Django 5.1.3 on 2024-12-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-created_at"]},
        ),
    ]
