# Generated by Django 4.2.7 on 2024-12-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_flyer',
        ),
        migrations.AddField(
            model_name='event',
            name='event_image_1',
            field=models.ImageField(null=True, upload_to='event_images'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image_2',
            field=models.ImageField(null=True, upload_to='event_images'),
        ),
    ]
