# Generated by Django 5.1.3 on 2024-12-02 11:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('report', models.TextField()),
                ('head_image', models.ImageField(blank=True, null=True, upload_to='news')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='news')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updted', models.DateTimeField(auto_now=True, null=True)),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
