# Generated by Django 4.2.7 on 2024-12-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='minutes_read',
            field=models.IntegerField(default=0),
        ),
    ]
