# Generated by Django 4.2.7 on 2025-01-05 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notifyuser_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifyuser',
            options={'verbose_name': 'Notify User', 'verbose_name_plural': 'Notify User'},
        ),
        migrations.AlterModelTable(
            name='notifyuser',
            table='notify_user',
        ),
    ]
