# Generated by Django 4.2.7 on 2025-01-07 09:54

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_contactus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactus",
            name="email",
        ),
        migrations.AddField(
            model_name="contactus",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
    ]
