# Generated by Django 5.1.3 on 2024-12-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
