# Generated by Django 5.1.3 on 2024-12-19 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executives", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executiveprofile",
            name="executive",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                to="executives.executive",
            ),
        ),
    ]
