# Generated by Django 4.2.7 on 2025-01-05 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveSocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('snapchat', 'Snapchat'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('twitch', 'Twitch'), ('flickr', 'Flickr'), ('quora', 'Quora'), ('medium', 'Medium'), ('github', 'GitHub'), ('slack', 'Slack')], max_length=255)),
                ('link', models.URLField()),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='executives.executive')),
            ],
            options={
                'db_table': 'executives_social_links',
            },
        ),
    ]
