# Generated by Django 4.2.7 on 2024-12-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0002_alter_executiveprofile_executive'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_images'),
        ),
        migrations.DeleteModel(
            name='ExecutiveProfile',
        ),
    ]
