# Generated by Django 4.2.7 on 2025-01-05 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0002_executivesociallinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executivesociallinks',
            options={'verbose_name': 'Executive social links', 'verbose_name_plural': 'Executive social links'},
        ),
    ]
