# Generated by Django 4.2.7 on 2024-12-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmailVerifcationCodes",
            new_name="PhoneVerifcationCodes",
        ),
        migrations.AlterModelOptions(
            name="phoneverifcationcodes",
            options={
                "verbose_name": "",
                "verbose_name_plural": "PhoneVerificationCodes",
            },
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="email_confirm",
            new_name="phone_confirm",
        ),
        migrations.AddField(
            model_name="customuser",
            name="index_number",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="index number"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
