# Generated by Django 4.2.7 on 2024-12-26 17:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_emailverifcationcodes_phoneverifcationcodes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneverifcationcodes',
            name='email',
        ),
        migrations.AddField(
            model_name='phoneverifcationcodes',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='phoneverifcationcodes',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
