# Generated by Django 4.2.7 on 2025-01-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_links_usersavedonlinetutorialtips_online_tips"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneverifcationcodes",
            name="expires_in",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
