# Generated by Django 4.2.7 on 2024-12-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_phoneverifcationcodes_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='graduation_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
