# Generated by Django 4.2.7 on 2024-12-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_graduation_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='index_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='index number'),
        ),
    ]
