# Generated by Django 4.2.7 on 2025-01-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_phoneverifcationcodes_expires_in"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="email",
        ),
    ]
