# Generated by Django 5.1.3 on 2024-12-02 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acadamics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
