# Generated by Django 4.2.7 on 2024-12-27 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acadamics', '0002_alter_course_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='course_code',
        ),
    ]
