# Generated by Django 4.2.7 on 2024-12-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acadamics', '0003_rename_course_name_course_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
