# Generated by Django 4.2.7 on 2024-12-29 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "ad_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("flyer", models.ImageField(upload_to="ads")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Advertisement",
                "verbose_name_plural": "Advertisements",
            },
        ),
    ]
