# Generated by Django 4.2.7 on 2024-12-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='approved',
            new_name='is_active',
        ),
    ]
