# Generated by Django 5.1.3 on 2024-12-20 08:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("acadamics", "0002_alter_course_course_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExaminationSystem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acadamics.course",
                    ),
                ),
            ],
        ),
    ]
