# Generated by Django 5.1.3 on 2024-12-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acadamics", "0002_alter_course_course_id"),
        ("examination_system", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExaminationSystem",
            new_name="ExaminationSchedule",
        ),
    ]
