# Generated by Django 5.1.3 on 2024-12-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination_system", "0002_rename_examinationsystem_examinationschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="examinationschedule",
            name="index_number_end",
            field=models.CharField(default=0, max_length=230),
        ),
        migrations.AddField(
            model_name="examinationschedule",
            name="index_number_start",
            field=models.CharField(default=0, max_length=230),
        ),
    ]
