# Generated by Django 4.2.7 on 2025-01-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination_system', '0002_alter_examinationschedule_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationschedule',
            name='message_schedule',
            field=models.DateTimeField(blank=True, help_text='The time a message is suppose to be sent all students who have this exam; If no time is set the system will send message 1 hour before the paper', null=True),
        ),
    ]
