# Generated by Django 5.1.3 on 2024-12-20 09:04

import django_google_maps.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination_system", "0003_examinationschedule_index_number_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examinationschedule",
            name="geolocation",
            field=django_google_maps.fields.GeoLocationField(
                blank=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="examinationschedule",
            name="location",
            field=models.CharField(max_length=230, null=True),
        ),
    ]
