# Generated by Django 5.1.4 on 2025-01-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination_system", "0003_examinationschedule_message_schedule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="examinationschedule",
            options={
                "verbose_name": "Examination Schedule Per Class",
                "verbose_name_plural": "Examination Schedules",
            },
        ),
        migrations.AlterField(
            model_name="examinationschedule",
            name="index_number_end",
            field=models.CharField(
                default=0,
                help_text="Last index number for that particular room",
                max_length=230,
            ),
        ),
        migrations.AlterField(
            model_name="examinationschedule",
            name="index_number_start",
            field=models.CharField(
                default=0,
                help_text="Starting index number for that particular room",
                max_length=230,
            ),
        ),
    ]
