# Generated by Django 5.1.3 on 2024-12-20 14:02

import django_google_maps.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("examination_system", "0004_examinationschedule_geolocation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examinationschedule",
            name="address",
            field=django_google_maps.fields.AddressField(max_length=200, null=True),
        ),
    ]
