# Generated by Django 5.1.4 on 2025-01-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination_system", "0004_alter_examinationschedule_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examinationschedule",
            name="action",
            field=models.CharField(
                choices=[
                    ("hold_scheduling", "hold_scheduling"),
                    ("schedule_message", "schedule_message"),
                ],
                default="hold_scheduling",
                help_text="Schedule Message Should Only Be Selected When Every Detail of The Examination Like Time And Location Is Confirm",
                max_length=255,
            ),
        ),
    ]
