# Generated by Django 5.1.4 on 2025-01-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination_system', '0005_examinationschedule_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationschedule',
            name='action',
            field=models.CharField(choices=[('hold_scheduling', 'Hold Scheduling'), ('schedule_message', 'Schedule Message')], default='hold_scheduling', help_text='Schedule Message Should Only Be Selected When Every Detail of The Examination Like Time And Location Is Confirm', max_length=255),
        ),
    ]
