# Generated by Django 5.1.3 on 2024-12-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination_system", "0007_examinationschedule_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="examinationschedule",
            name="time",
            field=models.DateTimeField(null=True),
        ),
    ]
