# Generated by Django 5.1.3 on 2024-12-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination_system", "0008_examinationschedule_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="examinationschedule",
            old_name="location",
            new_name="room",
        ),
        migrations.AddField(
            model_name="examinationschedule",
            name="college",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
