# Generated by Django 4.2.7 on 2025-01-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicslides",
            name="description",
            field=models.TextField(
                help_text="A simple description about the resource", null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="credit_hours",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="onlinetutorialtips",
            name="description",
            field=models.TextField(
                help_text="A simple description about the resource", null=True
            ),
        ),
        migrations.AddField(
            model_name="pastquestions",
            name="description",
            field=models.TextField(
                help_text="A simple description about the resource", null=True
            ),
        ),
        migrations.AlterField(
            model_name="onlinetutorialtips",
            name="type_of_resource",
            field=models.CharField(
                choices=[
                    ("slides", "slides"),
                    ("video", "video"),
                    ("article", "article"),
                    ("audio", "audio"),
                    ("file", "file"),
                ],
                max_length=50,
            ),
        ),
    ]
