# Generated by Django 4.2.7 on 2025-01-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_academicslides_description_course_credit_hours_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academicslides",
            name="description",
        ),
        migrations.RemoveField(
            model_name="onlinetutorialtips",
            name="description",
        ),
        migrations.RemoveField(
            model_name="pastquestions",
            name="description",
        ),
        migrations.AddField(
            model_name="academicslides",
            name="title",
            field=models.TextField(
                help_text="A simple title about the resource", null=True
            ),
        ),
        migrations.AddField(
            model_name="onlinetutorialtips",
            name="title",
            field=models.TextField(
                help_text="A simple title about the resource", null=True
            ),
        ),
        migrations.AddField(
            model_name="pastquestions",
            name="title",
            field=models.TextField(
                help_text="A simple title about the resource", null=True
            ),
        ),
    ]
