# Generated by Django 4.2.7 on 2025-01-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_remove_academicslides_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicslides",
            name="title",
            field=models.CharField(
                help_text="A simple title about the resource", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="onlinetutorialtips",
            name="title",
            field=models.CharField(
                help_text="A simple title about the resource", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pastquestions",
            name="title",
            field=models.CharField(
                help_text="A simple title about the resource", max_length=255, null=True
            ),
        ),
    ]
