# Generated by Django 5.1.4 on 2025-01-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_internshipopportunities_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="internshipopportunities",
            options={
                "verbose_name": "Internship",
                "verbose_name_plural": "Internships",
            },
        ),
        migrations.AlterField(
            model_name="internshipopportunities",
            name="image",
            field=models.ImageField(
                help_text="Image can be a flyer or the companies logo",
                null=True,
                upload_to="internships",
            ),
        ),
    ]
