# Generated by Django 5.1.4 on 2025-01-08 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('type_of_product', models.CharField(choices=[('cloth', 'cloth'), ('books', 'books'), ('utilities', 'utilities')], max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPayment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('transaction_validation_code', models.CharField(max_length=100, unique=True)),
                ('transaction', models.CharField(max_length=50)),
                ('payed_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Payed')),
                ('payment_successful', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'verbose_name': 'Product Payment',
                'verbose_name_plural': 'Product Payments',
                'db_table': 'product_payment',
            },
        ),
    ]
