# Generated by Django 5.1.4 on 2025-01-09 10:56

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_productpayment_transaction_validation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpayment",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
    ]
